
@baseUrl = http://localhost:3000


### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Film Test",
    "duration":155,
    "budget": 15,
    "link": "https://fr.wikipedia.org/wiki/Spider-Man"
}

### Delete pizza identified by 2
DELETE {{baseUrl}}/films/2

### Update the pizza identified by 6
PATCH {{baseUrl}}/films/3
Content-Type: application/json

{
    "title":"Tiago"
}

### PUT pizza identified by 4
PUT {{baseUrl}}/films/4
Content-Type: application/json

{
    "title":"Film4",
    "duration":34,
    "budget": 7,
    "link": "https://fr.wikipedia.org/wiki/Test"
}