### Create a pizza
### Read all pizzas with File variable
@baseUrl = http://localhost:3000
POST {{baseUrl}}/pizzas
Content-Type: application/json

{
    "title":"Magic Green",
    "content":"Epinards, Brocolis, Olives vertes, Basilic"
}
